# Vim: set et ts=2 sts=2 sw=2

language: rust

rust:
  - 1.34.2
  - stable

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - cargo install --force cargo-audit
  - cargo install --force cargo-tree

script:
  - cargo tree
  - cargo test --all --verbose
  - test -r 'Cargo.lock' && cargo audit
