# Vim: set et ts=2 sts=2 sw=2

language: rust

rust:
  - 1.34.2
  - stable

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - cargo install --force cargo-audit

script:
  - cargo test --all --verbose
  - cargo audit
