[package]
name = "irc-bot"
version = "0.1.0"
authors = ["c74d <8573dd@gmail.com>"]

[dependencies]
clap = "2"
env_logger = "0.4"
error-chain = "0.10"
irc = "0.11"
itertools = "0.6"
log = "0.3"
uuid = {version = "0.5", features = ["v4"]}
