[package]
name = "irc-bot"
version = "0.1.0"
authors = ["c74d <8573dd@gmail.com>"]
description = "A library for writing Internet Relay Chat (IRC) bots in Rust"
documentation = "https://docs.rs/irc-bot"
homepage = "https://docs.rs/crate/irc-bot"
repository = "https://github.com/8573/irc-bot.rs"
readme = "README.md"
keywords = ["irc", "internet-relay-chat", "internet_relay_chat", "bot", "bots"]
categories = ["network-programming"]
license = "Apache-2.0"

[dependencies]
bitflags = "1.0.1"
clap = "2.29.0"
crossbeam = "0.3.0"
crossbeam-channel = "0.1.2"
env_logger = "0.4.3"
error-chain = "0.10.0"
irc = "0.12.7"
itertools = "0.7.4"
lazy_static = "1.0.0"
log = "0.4.0"
parking_lot = "0.5.3"
serde = "1.0.26"
serde_derive = "1.0.26"
serde_yaml = "0.7.3"
uuid = {version = "0.5.1", features = ["v4"]}
yaml-rust = "0.4.0"
