nickname: bot74d
username: egbot
realname: egbot
servers:
  - name: OFTC
    host: irc.oftc.net
    port: 9999
    channels:
      - name: '#c74d'
      - name: '#rust-offtopic'
admins:
  - nick: c74d
    user: c74d
