nickname: bot74d
username: egbot
realname: egbot
servers:
  - name: Mozilla
    host: irc.mozilla.org
    port: 6697
    channels:
      - name: '#c74d'
      - name: '#rust-irc'
admins:
  - nick: c74d
    user: c74d
